apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: customer
    meta.helm.sh/release-namespace: database
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: customer
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-10.3.2
  name: customer-db-lb
  namespace: database
spec:
  ports:
    - name: mysql
      port: 13306
      protocol: TCP
      targetPort: 3306
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: customer
    app.kubernetes.io/name: mariadb
  type: LoadBalancer