apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: center
spec:
  replicas: 3
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: sparktype/config:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: center
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: config
---
apiVersion: v1
kind: Service
metadata:
  name: config-lb
  namespace: center
spec:
  type: LoadBalancer
  ports:
    - port: 18888
      targetPort: 8888
  selector:
    app: config