apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: center
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: app
          image: sparktype/eureka:1.0.2
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: center
  labels:
    app: eureka
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-ui
  namespace: center
  labels:
    app: eureka
spec:
  type: LoadBalancer
  ports:
    - port: 18761
      targetPort: 8761
  selector:
    app: eureka