spring:
  datasource:
    url: jdbc:mariadb://customer-mariadb.database.svc.cluster.local:3306/customer?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: developer
    password: pass1234
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.center.svc.cluster.local:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
